name: NoGuardian DNS

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install dnsmasq
      run: sudo apt-get update && sudo apt-get install dnsmasq -y

    - name: Copy dnsmasq configuration file
      run: |
        sudo cp /etc/dnsmasq.conf /etc/dnsmasq.conf.bak
        sudo rm /etc/dnsmasq.conf
        sudo touch /etc/dnsmasq.conf
        sudo chmod 777 /etc/dnsmasq.conf
        echo "server=8.8.8.8" >> /etc/dnsmasq.conf
        echo "server=8.8.4.4" >> /etc/dnsmasq.conf
        echo "address=/beacon-fullpage-predictor.goguardian.com/0.0.0.0" >> /etc/dnsmasq.conf
        echo "address=/x3-predictor.goguardian.com/0.0.0.0" >> /etc/dnsmasq.conf
        echo "address=/panther.goguardian.com/0.0.0.0" >> /etc/dnsmasq.conf
        echo "address=/ip.goguardian.com/0.0.0.0" >> /etc/dnsmasq.conf
        echo "address=/inquisition.goguardian.com/0.0.0.0" >> /etc/dnsmasq.conf
        echo "address=/countvoncount.goguardian.com/0.0.0.0" >> /etc/dnsmasq.conf
